### PR TITLE
profile page restyling merge with master

### PR DESCRIPTION
**Pull request by pojj**
Adding new changes to head branch. While keeping the updated Readme in master

### CODE REVIEW

**Review by ZhengThomas — APPROVED** [review]
this is all very nice

**Review by ZhengThomas — COMMENTED** [review]
thank you for renaming the bad naming practices

**Review by Sylvonir — COMMENTED** [review]
Changes look good

**Review by ZhengThomas — APPROVED** [review]
github is glitchy and needs me to approve again apparently
this is all good

**Pull request merged**
